import Header from '@/components/Header'
import Login from '@/components/Login'
import Head from 'next/head'
import Image from 'next/image'
import TodoPage from './TodoPage'


export default function Home() {
  return (
    <>
      <Head>
        <title>NextJS ToDo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header />
      <TodoPage />
    </>
  )
}